# Generated by Django 6.1 on 2026-08-24 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0002_alter_category_options_blog"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="is_fetured",
            new_name="is_featured",
        ),
    ]
