# Generated by Django 5.2.6 on 2026-08-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_about_created_at_alter_about_about_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="about_description",
            field=models.CharField(max_length=500),
        ),
    ]
