# Generated by Django 5.2.6 on 2026-08-25 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_about_about_description"),
    ]

    operations = [
        migrations.DeleteModel(
            name="About",
        ),
    ]
