# Generated by Django 5.2.6 on 2026-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0005_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="about",
            name="about_description",
            field=models.TextField(max_length=500),
        ),
    ]
